### ISSUE TITLE
running 'npm install' before restart

### ISSUE THREAD

**Issue by behumble** [keymetrics/pm2-auto-pull#16]
isn't it be great if it executes 'npm install' just before restart by modification?

**Comment by wiliam-paradox** [comment]
@behumble there is a post_update option in pm2, so I think that this plugin doesn't have the responsibility to do an npm install. Here are the docs:

http://pm2.keymetrics.io/docs/usage/pm2-doc-single-page/

**Comment by behumble** [comment]
Sorry I should had read the document more carefully. it seems sufficient.
