### ISSUE TITLE
App.js does not read interval value

### ISSUE THREAD

**Issue by losnir** [keymetrics/pm2-auto-pull#5]
The plugin constantly auto-pulls at intervals of 30 seconds (i.e. default value; 30000).

Line [64](https://github.com/pm2-hive/pm2-auto-pull/blob/master/app.js#L64): `}, 30000 || conf.interval);`

Lazy evaluation causes the first operand to always be returned.

**Comment by losnir** [comment]
Pull Request created: https://github.com/pm2-hive/pm2-auto-pull/pull/6.

**Comment by Unitech** [comment]
published 1.15.0

**Comment by losnir** [comment]
Thanks for the quick merge! Hooray. </delayed>
